### ISSUE TITLE
Namespace module bug

### ISSUE THREAD

**Issue by WalchAndreas** [krauthaufen/Adaptify#19] opened 2021-04-27 15:44 UTC

**Comment by haraldsteinlechner** [comment] 2021-05-06 15:05
two type entities with the same name in the same assembly may lead to exposion here: https://github.com/krauthaufen/Adaptify/commit/fcea54efd7d9048faaa1e4a955ea75a4de2673ae#diff-9fb1575b23ebba7cd9517e6998fa5d525e01f470b3374c9ce7435a3eb837966cL453

this is not caught, adaptify crashes, no types generated, no info about the problem.
@WalchAndreas at least emits error messages accordingly.

the problem is demonstrated here: https://github.com/krauthaufen/Adaptify/commit/d1f02b0a2a047b2d7b52e7cd3a8b76ed9d0789d1

**Comment by haraldsteinlechner** [comment] 2021-05-06 15:06
@WalchAndreas due to merge conflicts i merged your head into the PR mentioned above. this should solve the problem.

**Closed as completed by haraldsteinlechner** 2021-05-06 15:06 UTC
